### ISSUE TITLE
Компетенции

### ISSUE THREAD

**Issue by d4got10** [d4got10/platform-for-online-internships#13]
Круд для компетенций

Для компетенций стажёра - get список

Для должности - возвращать список компетенций и список курсов(join id + name)
Для курсов - возвращать список компетенций
 
Для курс/должность и курс/компетенция - post delete

**Comment by d4got10** [comment]
@Quatters  Нужно ли делать для компетенций списковые get запросы курсов и должностей, на которых они задействованы?

**Comment by Quatters** [comment]
> @Quatters  Нужно ли делать для компетенций списковые get запросы курсов и должностей, на которых они задействованы?

да наверное, можно будет показывать, что стажёру пройти надо, чтоб получить компетенцию например
