### ISSUE TITLE
Закрепление стажёров за наставником

### ISSUE THREAD

**Issue by d4got10** [d4got10/platform-for-online-internships#35]
При записи на должность стажёра, администратор закрепляет за ним наставника с этой должности.
Наставники видят задания на проверку только от тех студентов, за кем они закреплены.

**Comment by Quatters** [comment]
Предлагаю сделать так.

1. Делаем таблицу с fk полями на `teacher` и `intern` (оба на `user`). `intern` уникальные. Каскад на удаление любого поля.
2. Делаем вложенный эндпоинт на юзера (наставника), позволяющий проставить ему стажеров. Нужно учесть, что каждый проставленный стажер еще не распределен (нет наставника для него) и подходит по должности.
3. Чтобы показывать подходящих стажеров для распределения, делаем вложенный эндоинт на наставника, возвращающий стажеров без наставника и подходящих по должности.
4. На фронте для админа даем возможность проставить стажеров любому наставнику. Для наставника даем возможность проставлять своих стажеров.
5. При удалении должности у стажера если он прикреплен к наставнику, проверять, подходит ли он ему все еще, если нет, откреплять.
6. При удалении должности у наставника аналогично проверять всех его стажеров на совместимость и удалять неугодных.
