### ISSUE TITLE
Задания

### ISSUE THREAD

**Issue by Quatters** [d4got10/platform-for-online-internships#6]
[БД](https://github.com/d4got10/platform-for-online-internships/wiki)

Сущности:
* Задание.
* Тип задания (один вариант ответа, несколько вариантов ответа, текстовый ответ, эксель). Склоняюсь к тому, чтоб хранить в виде обычного enum в коде, т.к. типов фиксированное количество. Если делать так, неплохо будет добавить check constraint на строковое поле типа задания. Кроме того, такой вариант будет проще для API - [в схеме может ходить поле с типом enum](https://swagger.io/docs/specification/data-models/enums/).
* Ответ. Относится только к заданиям типа с одним вариантом ответа и несколькими вариантами ответа. Думаю можно добавить сюда поле вроде ``is_correct``. 
* Ответ пользователя. Относится ко всем заданиям. Поэтому поле "значение" текстовое. Для заданий с вариантами ответа в значении будет fk id на ответ. Для развернутого текст ответа. Для экселя ссылка на локальный файл/онлайн эксель.
* Попытка (id, user, topic, estimate, ?spent).

Также надо добавить для темы обучающего материала поле с временем прохождения всех связанных заданий, чтобы на фронте рисовать таймер. Либо не хранить это в БД, а, например, вычислять как сумму весов всех связанных заданий (типа с одним вариантом ответа стоит 1 мин, с несколькими 3 мин и т.д.). Последний вариант мне даже больше нравится. А сами веса если можно будет в `.env` задавать, вообще красота.

В API точно должны быть
* crud на   `/courses/{course_id}/topics/{topic_id}/tasks` (админ (crud), наставник (get))
* crud на   `/courses/{course_id}/topics/{topic_id}/tasks/{task_id}/answers` (админ (crud), наставник (get), слать 400, если не подходящий тип задания, `is_correct` слать только для админа)
* POST `/courses/{course_id}/topics/{topic_id}/make_attempt` для стажера. Создает запись в сущности Попытка и возвращает типа таких данных

(*)
```python
test_id: int,
estimate: <что-нибудь, можно int минут>,
tasks: [
    {
        task_id: int, 
        description: str, 
        type: str, 
        possible_answers: [
            {answer_id: int, value: str}
        ]
    },
]
```

``possible_answers`` можно не слать, если неподходящий тип задания. Слать 400, если роль пользователя не стажер. Слать 400, если уже есть тест для такого юзера и темы обучающего материала, у которого ``spent == null``.

* POST `/courses/{course_id}/topics/{topic_id}/submit_attempt` получает типа таких данных

```python
{    
    test_id: int,
    tasks: {
        task_id: str | int | int[]
    }
}
```
 
Если время для попытки вышло, сразу возращать 400. Думаю можно для этих случаев ставить общую оценку 0 и не делать ничего больше.

С обработкой этого делов конечно дофига. Проверить все задания на правильность типа присланного ответа, потом для всех заданий, у которых ответ - это fk, что такой ответ существует, потом еще посчитать оценку для автоматически проверяемых заданий, насоздавать наставнику записей в Результат задания, и насоздавать записей в Ответ пользователя. Надо посмотреть, как себя поведет fastapi, если сделать все это наивно в контроллере. Он вроде умеет в асинхронщину, но я не знаю, насколько хорошо. Либо заморочиться с асинхронным воркером, если ответ от сервера прям долгий будет.

Насчет количества попыток пока предлагаю не заморачиваться и давать возможность делать сколько угодно, но только на момент создания новой попытки еще нет текущей попытки.

* GET `/courses/{course_id}/topics/{topic_id}/attempts` - возвращает список попыток с данными из БД, попытки с ``spent == null`` исключать
* GET `/courses/{course_id}/topics/{topic_id}/attempts/{attempt_id}` - возвращает данные формата как в (*), только вместо `possible_answers` реальные ответы, а вместо `estimate` `spent`. Если запрашивается попытка с `spent == null`, возвращать 404.

**Comment by Quatters** [comment]
Зависит от https://github.com/d4got10/platform-for-online-internships/issues/2

**Comment by Quatters** [comment]
@d4got10 как-то так я все это вижу, хотя подумать тут еще есть над чем

**Comment by d4got10** [comment]
Нужно ли для сущности topic порядковый номер задавать?

**Comment by Quatters** [comment]
> Нужно ли для сущности topic порядковый номер задавать?

а что это и зачем?)

**Comment by d4got10** [comment]
/courses/{course_id}/topics/ для этих эндпоинтов
Я как понял у нас для курса есть их список тем, задания для них.
Они же в каком-то заданном порядке должны идти или пофиг?

**Comment by Quatters** [comment]
> /courses/{course_id}/topics/ для этих эндпоинтов Я как понял у нас для курса есть их список тем, задания для них. Они же в каком-то заданном порядке должны идти или пофиг?

а, да, надо бы сделать, и unique constraint на (course_id, номер) тогда

**Comment by Quatters** [comment]
> > /courses/{course_id}/topics/ для этих эндпоинтов Я как понял у нас для курса есть их список тем, задания для них. Они же в каком-то заданном порядке должны идти или пофиг?
> 
> а, да, надо бы сделать, и unique constraint на (course_id, номер) тогда

А может лучше тогда one-to-one на себя, типа `prev_topic`? Просто если номера, тогда может получиться, что у нас идут 1, 2, а потом 5. Или для следующего будем выдавать следующий наименьшим номер? Если так, то не очень интуитивно будет

**Comment by d4got10** [comment]
> 
Сделаю prev_topic
Еще вопрос, для запросов по id топика, например для GET /courses/{course_id}/topics/{topic_id} course_id избыточен.
Мне проверять, что он совпал со значением course_id в топике или не нужно?

**Comment by Quatters** [comment]
> Сделаю prev_topic Еще вопрос, для запросов по id топика, например для GET /courses/{course_id}/topics/{topic_id} course_id избыточен. Мне проверять, что он совпал со значением course_id в топике или не нужно?

предполагается, что `/courses/{course_id}/topics` выдает все топики для курса `course_id`, с `/courses/{course_id}/topics/{topic_id}` аналогично, т.е. если запрошен существующий топик, но не принадлежащий курсу, возвращать 404

**Comment by Quatters** [comment]
Для поддержки сторонних приложений хранить где-нибудь мапу поддерживаемых сторонних приложений, (напр. название -> ссылка на запуск), желательно сделать, чтобы админ мог задавать поддерживаемые приложения и пихать их в задания. Надо подумать над обработкой результата.
